<?php
/**
  * Function to build age verification box
  */

function cofirm(&$form) {
  $form['ageverificationbox'] = array(
    '#type' => 'checkbox', 
    '#title' => "I am over 18", 
    '#required' => TRUE,
    '#return_value' => 1,
    '#default_value' => 0,
  );
  $form['#validate'][] = 'ageverificationbox_validate';
}

/**
  * Implements hook_user_login()
  */
function login_change_form_user_login_alter(&$form, &$form_state) {
  cofirm($form);
}

/**
  * Implements hook_user_register_form()
  */
function login_change_form_user_register_form_alter(&$form, &$form_state) {
  cofirm($form);
}

/**
  * Implements hook_user_register_form()
  */
function login_change_form_user_login_block_alter(&$form, &$form_state) {
  cofirm($form);
}

/**
  * Validate function for age verification box 
  */ 
function ageverificationbox_validate(&$form, &$form_state) { 
  if ($form_state['values']['ageverificationbox'] == 0) {
    form_error($form, t('Age not validated.'));
  }
}
