<?php
/**
  * Function to build age verification box
  */
function login_change_verificate(&$form) {
  $form['age_verification_box'] = array(
    '#type' => 'checkbox', 
    '#title' => 'I am over 18',
    '#required' => TRUE,
  );
  $form['#validate'][] = 'login_change_age_verification_box_validate';
}

/**
  * Implements hook_form_alter()
  */
function login_change_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'user_login':
    case 'user_login_block':
    case 'user_register_form':
      login_change_verificate($form);
  }
}

/**
  * Validate function for age verification box
  */ 
function login_change_age_verification_box_validate(&$form, &$form_state) {
  if ($form_state['values']['age_verification_box'] == 0) {
    form_error($form, t('Age not validated.'));
  }
}